Fixed compilation issue for some distributions what have jsoncpp installed and its headers were in include path.
There are two json libraries : libjson-c and jsoncpp.
Both libraries have header with same name - json.h.
nfstrace uses libjson-c but on some linux distributions installed jsoncpp could cause
compilation errors.
Headers of jsoncpp library should not be in the include path.

Also /usr/include/json/features.h header from jsoncpp had issues with /usr/include/c++/6/parallel/features.h:
In file included from /usr/include/json/features.h:10:0,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/os_defines.h:39,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/c++config.h:482,
                 from /usr/include/c++/5/type_traits:38,
                 from /usr/include/c++/5/ratio:38,
                 from /usr/include/c++/5/chrono:38,
                 from .../nfstrace-0.4.3/analyzers/src/json/json_tcp_service.cpp:22:

Updated FindJSON.cmake to  include only libjson-c headers by
searching for json_c_version.h file which exists only for libjson-c.

Previously it included both /usr/include/json-c and /usr/include/json
which might not be desired as on some distributions headers of jsoncpp are located in /usr/include/json.

Debian and Ubuntu have json-c in /usr/include/json-c and jsoncpp in /usr/include/jsoncpp/json
Arch and Fedora have json-c in /usr/include/json-c and jsoncpp in /usr/include/json