nfstrace: fix format string specifiers detected by ncurses-6.3
`ncuses-6.3` added printf-style function attributes and now makes
it easier to catch cases when user input is used in palce of format
string when built with CFLAGS=-Werror=format-security:

    nfstrace/analyzers/src/watch/nc_windows/header_window.cpp:77:82:
      error: format '%d' expects argument of type 'int', but argument 5 has type 'time_t' {aka 'long int'} [-Werror=format=]
       77 |     mvwprintw(_window, HEADER::ELAPSED_LINE, FIRST_CHAR_POS, "Elapsed time:  \t %d days; %d:%d:%d times",
          |                                                                                 ~^
          |                                                                                  int
          |                                                                                 %ld